baseURL = 'https://matiasgreaker.github.io'
languageCode = 'en-us'
title = 'Matias notater'
theme = 'hugo-theme-nostyleplease'
canonifyURLs = true

[params]
  [params.theme_config]
    back_home_text    = "<--"
    isShowFooter      = false
    isListGroupByDate = true
